---
- name: "Copy nginx.conf"
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: "Copy application specific configuration files, for web redirects"
  vars:
    apps:
      plex:
        APP_NAME: plexlkasjd
        APP_PORT: 32400
      deluge:
        APP_NAME: delugelkasjdf
        APP_PORT: 8112
  template:
    src: app.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.APP_NAME }}.conf"
  with_items:
    - { APP_NAME: 'plex', APP_PORT: '32400' }
    - { APP_NAME: 'deluge', APP_PORT: '8112' }
    - { APP_NAME: 'sonarr', APP_PORT: '8989' }
    - { APP_NAME: 'sabnzbd', APP_PORT: '8080' }
    - { APP_NAME: 'mylar', APP_PORT: '8090' }
    - { APP_NAME: 'munin', APP_PORT: '8000' }
    - { APP_NAME: 'jdownloader', APP_PORT: '5800' }



#    - plex
#    - deluge
#  with_items: "{{ apps | list }}"


#    - { APP_NAME: 'plex', APP_PORT: '32400' }
#    - { APP_NAME: 'deluge', APP_PORT: '8112' }
#    - { APP_NAME: 'sonarr', APP_PORT: '8989' }
#    - { APP_NAME: 'sabnzbd', APP_PORT: '8080' }
#    - { APP_NAME: 'mylar', APP_PORT: '8090' }
#    - { APP_NAME: 'munin', APP_PORT: '8000' }
#    - { APP_NAME: 'jdownloader', APP_PORT: '5800' }
