---

# Here's the link to megatools git repo: https://github.com/megous/megatools
# We will try out megacmd first..

# megacmd from: https://mega.nz/cmd
- name: "Copy RPM file to remote server"
  copy:
    src: files/megacmd-CentOS_7.x86_64.rpm
    dest: /tmp
  
- name: "Install rpm from local file"
  yum:
    name: /tmp/megacmd-CentOS_7.x86_64.rpm
    state: present 

- name: "Copy .megarc file to ~kevinp/ (for megatools)"
  copy:
    src: files/.megarc
    dest: /home/kevinp
    group: kevinp
    owner: kevinp
    mode: 0664
