---

- name: "munin-node configuration"
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    group: root
    owner: root
    mode: 0644
  notify:
    - restart munin-node

- name: "Copy plex.repo"
  copy:
    src: files/plex.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  tags: host_plex 

- name: "Install Plex Media Server"
  yum:
    name: plexmediaserver
    state: latest
  tags: host_plex 
