---

- name: "Allow root login only on console"
  lineinfile:
    path: /etc/securetty
    state: present
    insertafter: EOF
    line: tty1

- name: "Secure root home"
  file:
    path: /root
    state: directory
    mode: 0700

- name: "Open relevant firewalld ports"
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - 32400 # Plex
    - 8112 # Deluge
    - 8989 # Sonarr
    - 8080 # Sabnzbd HTTP
    - 9090 # Sabnzbd HTTPS
    - 8090 # Mylar
    - 8000 # Munin
    - 5800 # JDownloader-2

- name: "Open relevant firewalld service ports"
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
    - nfs
    - nfs3
    - samba
    - samba-client
    - dns

#- name: "Change default SSH port"
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: '#Port 22'
#    line: 'Port {{ SSH_PORT }}'

#- name: "Allow port change through SELinux"
#  seport:
#    ports: "{{ SSH_PORT }}"
#    proto: tcp
#    setype: ssh_port_t
#    state: present
#  notify:
#    - restart sshd

