---

- name: "Update OS"
  yum:
    name: '*'
    state: latest

- name: "Enable EPEL repo"
  yum:
    name: epel-release
    state: present

- name: "Install Nux Dextop GPG key"
  rpm_key:
    key: http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
    state: present

- name: "Install Nux Dextop RPM repo"
  yum:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
    state: present

- name: "Install RPMFusion repo's"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm

- name: "Instal Plex Media Server repo file"
  copy:
    src: files/plex.repo
    dest: /etc/yum.repo.d
    mode: 0644
    force: yes

# Install additional packages for general administration usage
- name: "Install additional packages"
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - screen
    - rsync
    - wget
    - htop
    - bind-utils
    - nmap-ncat
    - chrony
    - sysstat
    - telnet
    - bind-utils
    - nmap
    - deltarpm
    - gcc
    - gcc-c++
    - policycoreutils-python
    - bash-completion
    - mlocate
    - munin-node
    - nginx
    - python2-certbot-nginx
    - ncompress
    - git
    - perl-Net-CIDR.noarch
    - httpd-tools
    - psmisc
    - ftp
    - links
    - lynx
    - ntfsprogs.x86_64
    - ntfs-3g.x86_64
    - yum-axelget
    - yum-fast-downloader
    - psmisc
    - lsof
    - vim
    - symlinks
    - yum-cron
    - smartmontools
  ignore_errors: yes
  tags: packages

- name: "SELinux httpd_can_network_connect on, to allow for NGINX web redirects"
  command:
    setsebool -P httpd_can_network_connect on

- name: "Restart chrony"
  systemd:
    name: chronyd
    state: restarted

- name: "set -o vi"
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: 'set -o vi'
