---

- name: "munin-node configuration"
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    group: root
    owner: root
    mode: 0644
  notify:
    - restart munin-node

- name: "Install Plex Media Server"
  yum:
    name: plexmediaserver
    state: latest
