---

- name: "Remove temporary directory"
  file:
    path: /tmp/git
    state: absent
    mode: 0755
    
- name: "Checkout some git repos for scripts"
  git:
    repo: "{{ item.URL }}" 
    dest: "{{ item.DESTDIR }}"
    force: yes
  with_items:
    - { URL: 'https://github.com/avatar333/bash-dnsactual.git', DESTDIR: /tmp/git/bash-dnsactual }
    - { URL: 'https://github.com/avatar333/bash-create-symlink-nests.git', DESTDIR: /tmp/git/bash-create-symlink-nests }
    - { URL: 'https://github.com/avatar333/bash-docker_versions.git', DESTDIR: /tmp/git/bash-docker_versions }
    - { URL: 'https://github.com/avatar333/bash-set-media-permissions.git', DESTDIR: /tmp/git/bash-set-media-permissions }

- name: "Copy scripts to /usr/local/bin"
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes
    force: yes
  with_items:
    - /tmp/git/bash-dnsactual/dnsactual.sh
    - /tmp/git/bash-create-symlink-nests/create-symlink-nests.sh
    - /tmp/git/bash-docker_versions/docker_versions.sh
    - /tmp/git/bash-set-media-permissions.sh

- name: "Copy root crontab"
  copy:
    src: files/root
    dest: /var/spool/cron
    mode: 0600
