---
# tasks file for ansible-role-dlm-configure-os

- include: configure_OS.yml
  tags: configure_OS

- include: configure_security.yml
  tags: configure_security

- include: configure_nginx.yml
  tags: configure_nginx

- include: configure_mega.yml
  tags: configure_mega

- include: configure_scripts_crontab.yml
  tags: configure_scripts_crontab

- include: configure_direct-lvm_thinpool.yml
  tags: configure_direct-lvm_thinpool

#- include: configure_host_apps.yml
#  tags: configure_host_apps
