---
# handlers file for ansible-role-dlm-configure-os
- name: "restart sshd"
  service:
    name: sshd
    state: restarted

- name: "restart munin-node"
  systemd:
    name: munin-node
    daemon_reload: yes
    enabled: yes
    state: restarted
